### ISSUE TITLE
Apparently the "number" is not issued anymore

### ISSUE THREAD

**Issue by kmindi** [latextemplates/uni-stuttgart-computer-science-cover#12]
The official template has not been updated http://www.informatik.uni-stuttgart.de/fachbereich/gremien/pruefungsausschuesse/Formulare/StADA_Titelseite.pdf

I have no official confirmation about this.

**Comment by koppor** [comment]
See https://github.com/latextemplates/scientific-thesis-template/pull/52 for a solution.

**Comment by koppor** [comment]
Duplicate of https://github.com/latextemplates/scientific-thesis-template/issues/51
